Document: sreader-0.0.1
Title: Debian sreader-0.0.1 Manual
Author: <insert document author here>
Abstract: This manual describes what sreader-0.0.1 is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/sreader-0.0.1/sreader-0.0.1.sgml.gz

Format: postscript
Files: /usr/share/doc/sreader-0.0.1/sreader-0.0.1.ps.gz

Format: text
Files: /usr/share/doc/sreader-0.0.1/sreader-0.0.1.text.gz

Format: HTML
Index: /usr/share/doc/sreader-0.0.1/html/index.html
Files: /usr/share/doc/sreader-0.0.1/html/*.html
