Document: sreader
Title: Debian sreader Manual
Author: <insert document author here>
Abstract: This manual describes what sreader is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/sreader/sreader.sgml.gz

Format: postscript
Files: /usr/share/doc/sreader/sreader.ps.gz

Format: text
Files: /usr/share/doc/sreader/sreader.text.gz

Format: HTML
Index: /usr/share/doc/sreader/html/index.html
Files: /usr/share/doc/sreader/html/*.html

  
